server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bisbill?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Qordlstn0417#
    #    url: jdbc:h2:mem:isbill
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver
  hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    charSet: utf-8

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: update
    show-sql: true
    hibernate:
      ddl-auto: update
#      실행되는 쿼리 콘솔 출력
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
