spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:isbill
    username: sa
    password:
    driver-class-name: org.h2.Driver